### ISSUE TITLE
Syntax highlighting for RegEx with 'm' modifier

### ISSUE THREAD

**Issue by dstratossong** [atom/language-perl#72] opened 2016-05-13 15:05 UTC
It seems the `m` modifier (stands for multi-line matching) is not recognized as a modifier but begins as a new RegEx matcher. 

Example code:

```perl
if ($out =~ m/^(\d+)\s*$/m) { $pid = $1; }
```

Result: 

![perl-language-regex-highlight issue](https://cloud.githubusercontent.com/assets/8782072/15252157/9fabc968-18fa-11e6-9651-9e42150f6eb1.jpg)

**Comment by 50Wliu** [comment] 2016-05-13 16:04
Duplicate of #61 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-13 16:04 UTC
